language: java
jdk: oraclejdk8

services:
  - postgresql

before_install:
  - chmod +x mvnw

dist: trusty

deploy:
  provider: heroku
  api_key: a59bde74-e9e3-4173-a924-61d3eaa20fd8
  app: dr-help-backend