sudo: required
language: java
jdk: oraclejdk8

services:
  - postgresql

before_install:
  - chmod +x mvnw


addons:
  sonarcloud:
    organization: "tiberlas"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

script:
  - ./mvnw clean install -DskipTests=false -B
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

dist: trusty

deploy:
provider: heroku
api_key: $HEROKU_API_KEY
app: dr-help-backend